ALTER TABLE users
ADD COLUMN IF NOT EXISTS email VARCHAR;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS profession VARCHAR;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS password_hash VARCHAR;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS temp_password VARCHAR;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS temp_password_expires TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS onboarding_step VARCHAR DEFAULT 'INITIAL';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS onboarding_data JSONB;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_status VARCHAR DEFAULT 'TRIAL';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS trial_start_date TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS trial_end_date TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_end_date TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS tour_completed BOOLEAN DEFAULT FALSE;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS tour_current_step VARCHAR;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS language_preference VARCHAR(10) NOT NULL DEFAULT 'en';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS timezone_preference VARCHAR(64) NOT NULL DEFAULT 'America/New_York';

ALTER TABLE users
ADD COLUMN IF NOT EXISTS tour_completed_steps JSONB;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP DEFAULT NOW();

ALTER TABLE users
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
