import { useEffect, useMemo, useState } from 'react';
import { AddMeetingModal, MeetingDetail } from './Meetings';

const TABS = ['Overview', 'Timeline', 'Scope & Deliverables', 'Team & Stakeholders', 'Meetings', 'Risks'];
const statusStyle = { active: 'bg-emerald-100 text-emerald-800', paused: 'bg-amber-100 text-amber-800', completed: 'bg-slate-200 text-slate-700' };
const textOf = (value) => typeof value === 'string' ? value : value?.name || value?.title || value?.deliverable || value?.risk || 'Untitled';
const lines = (value) => String(value || '').split('\n').map((item) => item.trim()).filter(Boolean);

function Empty({ children = 'No information captured yet.' }) { return <p className="text-sm italic text-slate-400">{children}</p>; }

function Card({ title, editing, onEdit, onCancel, onSave, children, editor }) {
  return <section className="rounded-xl border border-slate-200 p-5"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold text-slate-950">{title}</h2>{editing ? <div className="flex gap-2"><button onClick={onCancel} className="rounded-lg border px-3 py-1.5 text-sm font-semibold">Cancel</button><button onClick={onSave} className="rounded-lg bg-blue-600 px-3 py-1.5 text-sm font-semibold text-white">Save</button></div> : <button onClick={onEdit} className="rounded-lg border border-slate-300 px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit</button>}</div>{editing ? editor : children}</section>;
}

function EditableTextCard({ title, value, multiline = true, onSave, empty }) {
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(value || '');
  useEffect(() => { if (!editing) setDraft(value || ''); }, [value, editing]);
  const editor = multiline ? <textarea rows={5} value={draft} onChange={(e) => setDraft(e.target.value)} className="w-full rounded-lg border border-slate-300 p-3" /> : <input value={draft} onChange={(e) => setDraft(e.target.value)} className="w-full rounded-lg border border-slate-300 p-3" />;
  return <Card title={title} editing={editing} onEdit={() => setEditing(true)} onCancel={() => setEditing(false)} onSave={async () => { await onSave(draft); setEditing(false); }} editor={editor}>{value ? <p className="whitespace-pre-line leading-7 text-slate-700">{value}</p> : <Empty>{empty}</Empty>}</Card>;
}

function EditableListCard({ title, values = [], onSave }) {
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState('');
  useEffect(() => { if (!editing) setDraft((values || []).map(textOf).join('\n')); }, [values, editing]);
  return <Card title={title} editing={editing} onEdit={() => setEditing(true)} onCancel={() => setEditing(false)} onSave={async () => { await onSave(lines(draft)); setEditing(false); }} editor={<textarea rows={7} value={draft} onChange={(e) => setDraft(e.target.value)} className="w-full rounded-lg border border-slate-300 p-3" placeholder="One item per line" />}>{values?.length ? <ul className="space-y-2">{values.map((item, index) => <li key={index} className="flex gap-2 text-slate-700"><span className="text-blue-600">•</span><span>{textOf(item)}</span></li>)}</ul> : <Empty />}</Card>;
}

function Timeline({ items = [], onSave }) {
  const normalized = items.map((item) => typeof item === 'string' ? { workstream: item } : item);
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(normalized);
  useEffect(() => { if (!editing) setDraft(normalized); }, [items, editing]);
  const update = (index, field, value) => setDraft((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  const editor = <div className="space-y-3">{draft.map((item, index) => <div key={index} className="grid gap-2 rounded-lg bg-slate-50 p-3 md:grid-cols-6">{[['workstream','Workstream'],['deliverable','Activity / deliverable'],['start','Start'],['finish','Finish'],['due','Deadline'],['owner','Owner']].map(([field, label]) => <label key={field} className="text-xs font-semibold text-slate-500">{label}<input value={item[field] || ''} onChange={(e) => update(index, field, e.target.value)} className="mt-1 w-full rounded border bg-white px-2 py-2 text-sm text-slate-800" /></label>)}<button onClick={() => setDraft((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="text-left text-xs font-semibold text-red-600 md:col-span-6">Remove row</button></div>)}<button onClick={() => setDraft((current) => [...current, {}])} className="rounded-lg border border-blue-300 px-3 py-2 text-sm font-semibold text-blue-700">Add timeline item</button></div>;
  return <Card title="Integrated project timeline" editing={editing} onEdit={() => setEditing(true)} onCancel={() => setEditing(false)} onSave={async () => { await onSave(draft.filter((item) => Object.values(item).some(Boolean))); setEditing(false); }} editor={editor}>{normalized.length ? <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{['Workstream','Activity / deliverable','Start','Finish','Deadline','Owner'].map((label) => <th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody className="divide-y">{normalized.map((item, index) => <tr key={index}><td className="px-3 py-4 font-semibold">{item.workstream || '—'}</td><td className="px-3 py-4">{item.deliverable || item.activity || '—'}</td><td className="px-3 py-4">{item.start || '—'}</td><td className="px-3 py-4">{item.finish || '—'}</td><td className="px-3 py-4 font-medium text-amber-700">{item.due || '—'}</td><td className="px-3 py-4">{item.owner || '—'}</td></tr>)}</tbody></table></div> : <Empty>Upload a proposal or add workstreams, dates, and deadlines.</Empty>}</Card>;
}

function PeopleCard({ title, values = [], people, onSave }) {
  const [selected, setSelected] = useState('');
  const add = () => { const person = people.find((item) => String(item.id) === selected); if (!person) return; if (!values.some((item) => Number(item?.person_id) === person.id)) onSave([...values, { person_id: person.id, name: person.name, role: person.relation || '', source: 'my_team' }]); setSelected(''); };
  const remove = (index) => onSave(values.filter((_, itemIndex) => itemIndex !== index));
  return <section className="rounded-xl border border-slate-200 p-5"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-4 flex gap-2"><select value={selected} onChange={(e) => setSelected(e.target.value)} className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2"><option value="">Add someone from My Team…</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name}{person.relation ? ` — ${person.relation}` : ''}</option>)}</select><button disabled={!selected} onClick={add} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Add</button></div><div className="mt-4 space-y-2">{values.map((person, index) => <div key={`${person?.person_id || textOf(person)}-${index}`} className="flex items-center justify-between rounded-lg bg-slate-50 p-3"><div><p className="font-semibold">{textOf(person)}</p>{person?.role && <p className="text-sm text-slate-500">{person.role}</p>}</div><button onClick={() => remove(index)} className="text-sm font-semibold text-red-600">Remove</button></div>)}{!values.length && <Empty>No one linked yet.</Empty>}</div></section>;
}

function ProjectForm({ project, onSave, onCancel }) {
  const [form, setForm] = useState(project || { project_name: '', status: 'active' }); const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-semibold">{project ? 'Edit Project' : 'New Project'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium">Project name<input autoFocus value={form.project_name || ''} onChange={(e) => update('project_name', e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>{[['client','Client'],['role','Role']].map(([key,label]) => <label key={key} className="text-sm font-medium">{label}<input value={form[key] || ''} onChange={(e) => update(key, e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>)}<label className="text-sm font-medium">Status<select value={form.status || 'active'} onChange={(e) => update('status', e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} className="rounded-lg border px-4 py-2 font-semibold">Cancel</button><button disabled={!form.project_name?.trim()} onClick={() => onSave(form)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Save Project</button></div></div></div>;
}

export default function Projects({ apiUrl, userNumber }) {
  const [projects, setProjects] = useState([]); const [project, setProject] = useState(null); const [tab, setTab] = useState('Overview'); const [people, setPeople] = useState([]);
  const [modal, setModal] = useState(false); const [meetingModal, setMeetingModal] = useState(false); const [meeting, setMeeting] = useState(null); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState('');
  const loadProjects = async () => { const response = await fetch(`${apiUrl}/api/projects?user_number=${encodeURIComponent(userNumber)}`); if (response.ok) setProjects(await response.json()); };
  const loadProject = async (id) => { const response = await fetch(`${apiUrl}/api/projects/${id}?user_number=${encodeURIComponent(userNumber)}`); if (response.ok) setProject(await response.json()); };
  const loadMeeting = async (id) => { const response = await fetch(`${apiUrl}/api/meetings/${id}?user_number=${encodeURIComponent(userNumber)}`); if (response.ok) setMeeting(await response.json()); };
  useEffect(() => { loadProjects(); fetch(`${apiUrl}/api/journey/people?user_number=${encodeURIComponent(userNumber)}`).then((response) => response.ok ? response.json() : []).then(setPeople).catch(() => setPeople([])); }, [userNumber]);
  const processingKey = useMemo(() => project?.documents?.map((doc) => `${doc.id}:${doc.processing_status}`).join('|') || '', [project?.documents]);
  useEffect(() => { if (!project?.id || !project.documents?.some((doc) => ['queued','extracting','analyzing'].includes(doc.processing_status))) return undefined; const interval = window.setInterval(() => loadProject(project.id), 3000); return () => window.clearInterval(interval); }, [project?.id, processingKey]);
  const save = async (form) => { const updating = Boolean(project); const response = await fetch(updating ? `${apiUrl}/api/projects/${project.id}?user_number=${encodeURIComponent(userNumber)}` : `${apiUrl}/api/projects?user_number=${encodeURIComponent(userNumber)}`, {method: updating ? 'PATCH' : 'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(form)}); if (response.ok) { const saved = await response.json(); setModal(false); await loadProjects(); await loadProject(saved.id); } };
  const patch = async (changes) => { const response = await fetch(`${apiUrl}/api/projects/${project.id}?user_number=${encodeURIComponent(userNumber)}`, {method:'PATCH', headers:{'Content-Type':'application/json'}, body:JSON.stringify(changes)}); if (response.ok) setProject(await response.json()); };
  const upload = async (file) => { if (!file) return; setUploading(true); setUploadError(''); const body = new FormData(); body.append('user_number', userNumber); body.append('file', file); try { const response = await fetch(`${apiUrl}/api/projects/${project.id}/documents`, {method:'POST',body}); if (!response.ok) throw new Error((await response.json()).detail || 'Could not upload this file.'); await loadProject(project.id); } catch (error) { setUploadError(error.message); } finally { setUploading(false); } };
  const retryDocument = async (id) => { await fetch(`${apiUrl}/api/projects/${project.id}/documents/${id}/retry?user_number=${encodeURIComponent(userNumber)}`, {method:'POST'}); loadProject(project.id); };
  if (meeting) return <MeetingDetail meeting={meeting} apiUrl={apiUrl} userNumber={userNumber} onBack={() => setMeeting(null)} onChanged={loadMeeting} onDeleted={() => { setMeeting(null); loadProject(project.id); }} />;
  if (!project) return <div className="mx-auto max-w-7xl p-5 lg:p-10"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-violet-600">Alfred's Project Memory</p><h1 className="mt-1 text-3xl font-semibold">My Projects</h1><p className="mt-2 text-slate-600">The context, people, meetings, and decisions behind every important initiative.</p></div><button onClick={() => setModal(true)} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">New Project</button></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((item) => <button key={item.id} onClick={() => loadProject(item.id)} className="rounded-2xl border bg-white p-6 text-left shadow-sm hover:border-blue-400"><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold">{item.project_name}</h2><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${statusStyle[item.status] || statusStyle.active}`}>{item.status}</span></div><p className="mt-2 text-sm text-slate-500">{item.client || 'No client'}{item.role ? ` · ${item.role}` : ''}</p><p className="mt-4 line-clamp-3 text-slate-700">{item.objective || item.description || 'Add the project objective and context.'}</p></button>)}</div>{!projects.length && <div className="mt-10 rounded-2xl border-2 border-dashed p-12 text-center"><h2 className="text-xl font-semibold">Create your first project memory</h2></div>}{modal && <ProjectForm onSave={save} onCancel={() => setModal(false)} />}</div>;
  return <div className="mx-auto max-w-7xl p-5 lg:p-10"><button onClick={() => {setProject(null);setTab('Overview');}} className="text-sm font-semibold text-blue-600">← All projects</button><div className="mt-5 rounded-2xl bg-slate-900 p-7 text-white"><div className="flex flex-wrap justify-between gap-5"><div><h1 className="text-3xl font-semibold">{project.project_name}</h1><p className="mt-3 text-slate-300">{project.client || 'No client'} · {project.role || 'Role not set'} · <span className="capitalize">{project.status}</span></p></div><div className="flex flex-wrap gap-3"><label className="cursor-pointer rounded-lg border border-white/30 px-4 py-2 font-semibold">{uploading ? 'Uploading…' : 'Upload Files'}<input type="file" accept=".pptx,.docx,.pdf,.txt,.md,.csv" className="sr-only" onChange={(e) => upload(e.target.files?.[0])} /></label><button onClick={() => setMeetingModal(true)} className="rounded-lg bg-blue-500 px-4 py-2 font-semibold">Record Meeting</button><button onClick={() => setModal(true)} className="rounded-lg border border-white/30 px-4 py-2 font-semibold">Edit Project</button></div></div></div><div className="mt-6 flex gap-1 overflow-x-auto border-b">{TABS.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap px-4 py-3 text-sm font-semibold ${tab===item?'border-b-2 border-blue-600 text-blue-700':'text-slate-500'}`}>{item}</button>)}</div><div className="mt-6 space-y-5 rounded-2xl border bg-white p-6 shadow-sm">
    {tab === 'Overview' && <><div className="grid gap-5 lg:grid-cols-2"><EditableTextCard title="Project summary" value={project.description} onSave={(description) => patch({description})} /><EditableTextCard title="Objective" value={project.objective} onSave={(objective) => patch({objective})} /><EditableTextCard title="Overall timing" value={project.timeline} multiline={false} onSave={(timeline) => patch({timeline})} /><EditableTextCard title="Alfred's overview" value={project.ai_overview} onSave={(ai_overview) => patch({ai_overview})} /></div><section className="rounded-xl border p-5"><h2 className="text-lg font-semibold">Files</h2>{uploadError && <p className="mt-2 rounded-lg bg-red-50 p-3 text-sm text-red-700">{uploadError}</p>}<div className="mt-3 space-y-2">{project.documents?.map((doc) => <div key={doc.id} className="rounded-lg bg-slate-50 p-3"><div className="flex justify-between gap-3"><a className="truncate text-blue-700" href={`${apiUrl}/api/projects/${project.id}/documents/${doc.id}?user_number=${encodeURIComponent(userNumber)}`}>{doc.filename}</a><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-semibold ${doc.processing_status==='ready'?'bg-green-100 text-green-800':doc.processing_status==='failed'?'bg-red-100 text-red-800':'bg-blue-100 text-blue-800'}`}>{doc.processing_status==='ready'?'Context added':doc.processing_status==='failed'?'Needs attention':'Alfred is analyzing'}</span></div>{doc.processing_error && <div className="mt-2 text-sm text-red-700"><p>{doc.processing_error}</p><button onClick={() => retryDocument(doc.id)} className="mt-1 font-semibold underline">Retry analysis</button></div>}</div>)}{!project.documents?.length && <Empty>No project files yet.</Empty>}</div></section></>}
    {tab === 'Timeline' && <><div className="rounded-xl bg-blue-50 p-4 text-sm text-blue-900"><strong>One integrated schedule.</strong> Alfred extracts workstreams, activities, start and finish timing, deadlines, and owners from every project document.</div><Timeline items={project.workplan || []} onSave={(workplan) => patch({workplan})} /></>}
    {tab === 'Scope & Deliverables' && <div className="grid gap-5 lg:grid-cols-3"><EditableListCard title="In Scope" values={project.in_scope} onSave={(in_scope) => patch({in_scope})} /><EditableListCard title="Out of Scope" values={project.out_of_scope} onSave={(out_of_scope) => patch({out_of_scope})} /><EditableListCard title="Deliverables" values={project.deliverables} onSave={(deliverables) => patch({deliverables})} /></div>}
    {tab === 'Team & Stakeholders' && <div className="grid gap-5 lg:grid-cols-2"><PeopleCard title="Core Team" values={project.core_team || []} people={people} onSave={(core_team) => patch({core_team})} /><PeopleCard title="Client Stakeholders" values={project.client_stakeholders || []} people={people} onSave={(client_stakeholders) => patch({client_stakeholders})} /></div>}
    {tab === 'Meetings' && <section><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Project meetings</h2><p className="text-sm text-slate-500">Existing Meeting Notes records linked to this project.</p></div><button onClick={() => setMeetingModal(true)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Record Meeting</button></div><div className="mt-5 divide-y">{project.meetings?.map((item) => <button key={item.id} onClick={() => loadMeeting(item.id)} className="grid w-full gap-2 py-4 text-left md:grid-cols-[140px_1fr_1fr_2fr]"><span>{item.started_at?new Date(item.started_at).toLocaleDateString():'No date'}</span><strong>{item.title}</strong><span>{item.participants?.join(', ')||'—'}</span><span>{item.one_line_summary||'Processing…'}</span></button>)}{!project.meetings?.length&&<Empty>No meetings linked yet.</Empty>}</div></section>}
    {tab === 'Risks' && <EditableListCard title="Project risks" values={project.risks} onSave={(risks) => patch({risks})} />}
  </div>{modal&&<ProjectForm project={project} onSave={save} onCancel={()=>setModal(false)} />}{meetingModal&&<AddMeetingModal apiUrl={apiUrl} userNumber={userNumber} projectId={project.id} onClose={()=>setMeetingModal(false)} onCreated={({id})=>{setMeetingModal(false);loadProject(project.id);loadMeeting(id);}} />}</div>;
}
