import { useEffect, useState } from 'react';
import { AddMeetingModal, MeetingDetail } from './Meetings';

const TABS = ['Overview', 'Workplan', 'Scope & Deliverables', 'Team & Stakeholders', 'Meetings', 'Risks'];
const statusStyle = { active: 'bg-emerald-100 text-emerald-800', paused: 'bg-amber-100 text-amber-800', completed: 'bg-slate-200 text-slate-700' };

const lines = (value) => String(value || '').split('\n').map((item) => item.trim()).filter(Boolean);
const displayValue = (value) => typeof value === 'string' ? value : value?.name || value?.title || value?.deliverable || 'Untitled';

function ListEditor({ title, values = [], onChange, placeholder }) {
  return <label className="block"><span className="text-sm font-semibold text-slate-800">{title}</span><textarea rows={6} value={(values || []).map(displayValue).join('\n')} onChange={(event) => onChange(lines(event.target.value))} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm" /></label>;
}

function ProjectForm({ project, onSave, onCancel }) {
  const [form, setForm] = useState(project || { project_name: '', status: 'active' });
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-2xl font-semibold">{project ? 'Edit Project' : 'New Project'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium">Project name<input autoFocus value={form.project_name || ''} onChange={(e) => update('project_name', e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>{[['client','Client'],['role','Role']].map(([key,label]) => <label key={key} className="text-sm font-medium">{label}<input value={form[key] || ''} onChange={(e) => update(key, e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label>)}<label className="text-sm font-medium">Status<select value={form.status || 'active'} onChange={(e) => update('status', e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2"><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label><label className="sm:col-span-2 text-sm font-medium">Objective<textarea rows={3} value={form.objective || ''} onChange={(e) => update('objective', e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2" /></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={onCancel} className="rounded-lg border px-4 py-2 font-semibold">Cancel</button><button disabled={!form.project_name?.trim()} onClick={() => onSave(form)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white disabled:opacity-40">Save Project</button></div></div></div>;
}

export default function Projects({ apiUrl, userNumber }) {
  const [projects, setProjects] = useState([]); const [project, setProject] = useState(null); const [tab, setTab] = useState('Overview');
  const [modal, setModal] = useState(false); const [meetingModal, setMeetingModal] = useState(false); const [meeting, setMeeting] = useState(null); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState('');
  const loadProjects = async () => { const response = await fetch(`${apiUrl}/api/projects?user_number=${encodeURIComponent(userNumber)}`); if (response.ok) setProjects(await response.json()); };
  const loadProject = async (id) => { const response = await fetch(`${apiUrl}/api/projects/${id}?user_number=${encodeURIComponent(userNumber)}`); if (response.ok) setProject(await response.json()); };
  const loadMeeting = async (id) => { const response = await fetch(`${apiUrl}/api/meetings/${id}?user_number=${encodeURIComponent(userNumber)}`); if (response.ok) setMeeting(await response.json()); };
  useEffect(() => { loadProjects(); }, [userNumber]);
  useEffect(() => {
    if (!project?.id || !project.documents?.some((doc) => ['queued', 'extracting', 'analyzing'].includes(doc.processing_status))) return undefined;
    const interval = window.setInterval(() => loadProject(project.id), 3000);
    return () => window.clearInterval(interval);
  }, [project?.id, project?.documents]);
  const save = async (form) => { const updating = Boolean(project); const response = await fetch(updating ? `${apiUrl}/api/projects/${project.id}?user_number=${encodeURIComponent(userNumber)}` : `${apiUrl}/api/projects?user_number=${encodeURIComponent(userNumber)}`, { method: updating ? 'PATCH' : 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(form) }); if (response.ok) { const saved = await response.json(); setModal(false); await loadProjects(); await loadProject(saved.id); } };
  const patch = async (changes) => { const response = await fetch(`${apiUrl}/api/projects/${project.id}?user_number=${encodeURIComponent(userNumber)}`, { method: 'PATCH', headers: {'Content-Type':'application/json'}, body: JSON.stringify(changes) }); if (response.ok) setProject(await response.json()); };
  const upload = async (file) => { if (!file) return; setUploading(true); setUploadError(''); const body = new FormData(); body.append('user_number', userNumber); body.append('file', file); try { const response = await fetch(`${apiUrl}/api/projects/${project.id}/documents`, {method:'POST', body}); if (!response.ok) throw new Error((await response.json()).detail || 'Could not upload this file.'); await loadProject(project.id); } catch (error) { setUploadError(error.message); } finally { setUploading(false); } };
  const retryDocument = async (documentId) => { setUploadError(''); const response = await fetch(`${apiUrl}/api/projects/${project.id}/documents/${documentId}/retry?user_number=${encodeURIComponent(userNumber)}`, {method:'POST'}); if (response.ok) loadProject(project.id); else setUploadError('Could not retry document analysis.'); };

  if (meeting) return <MeetingDetail meeting={meeting} apiUrl={apiUrl} userNumber={userNumber} onBack={() => setMeeting(null)} onChanged={loadMeeting} onDeleted={() => { setMeeting(null); loadProject(project.id); }} />;
  if (!project) return <div className="mx-auto max-w-7xl p-5 lg:p-10"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-violet-600">Alfred's Project Memory</p><h1 className="mt-1 text-3xl font-semibold">My Projects</h1><p className="mt-2 text-slate-600">The context, people, meetings, and decisions behind every important initiative.</p></div><button onClick={() => setModal(true)} className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">New Project</button></div>{projects.length ? <div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map((item) => <button key={item.id} onClick={() => loadProject(item.id)} className="rounded-2xl border bg-white p-6 text-left shadow-sm hover:border-blue-400"><div className="flex justify-between gap-3"><h2 className="text-xl font-semibold">{item.project_name}</h2><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${statusStyle[item.status] || statusStyle.active}`}>{item.status}</span></div><p className="mt-2 text-sm text-slate-500">{item.client || 'No client'}{item.role ? ` · ${item.role}` : ''}</p><p className="mt-4 line-clamp-3 text-slate-700">{item.objective || item.description || 'Add the project objective and context.'}</p></button>)}</div> : <div className="mt-10 rounded-2xl border-2 border-dashed p-12 text-center"><h2 className="text-xl font-semibold">Create your first project memory</h2><p className="mt-2 text-slate-600">Bring documents, meetings, stakeholders, and risks together.</p></div>}{modal && <ProjectForm onSave={save} onCancel={() => setModal(false)} />}</div>;

  return <div className="mx-auto max-w-7xl p-5 lg:p-10"><button onClick={() => {setProject(null); setTab('Overview');}} className="text-sm font-semibold text-blue-600">← All projects</button><div className="mt-5 rounded-2xl bg-slate-900 p-7 text-white"><div className="flex flex-wrap justify-between gap-5"><div><h1 className="text-3xl font-semibold">{project.project_name}</h1><p className="mt-3 text-slate-300">{project.client || 'No client'} · {project.role || 'Role not set'} · <span className="capitalize">{project.status}</span></p></div><div className="flex flex-wrap gap-3"><label className="cursor-pointer rounded-lg border border-white/30 px-4 py-2 font-semibold hover:bg-white/10">{uploading ? 'Uploading…' : 'Upload Files'}<input type="file" className="sr-only" onChange={(e) => upload(e.target.files?.[0])} /></label><button onClick={() => setMeetingModal(true)} className="rounded-lg bg-blue-500 px-4 py-2 font-semibold">Record Meeting</button><button onClick={() => setModal(true)} className="rounded-lg border border-white/30 px-4 py-2 font-semibold">Edit</button></div></div></div><div className="mt-6 flex gap-1 overflow-x-auto border-b">{TABS.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap px-4 py-3 text-sm font-semibold ${tab === item ? 'border-b-2 border-blue-600 text-blue-700' : 'text-slate-500'}`}>{item}</button>)}</div><div className="mt-6 rounded-2xl border bg-white p-6 shadow-sm">
    {tab === 'Overview' && <div className="grid gap-6 lg:grid-cols-2"><div><h2 className="text-lg font-semibold">Project summary</h2><textarea rows={6} value={project.description || ''} onChange={(e) => setProject({...project, description:e.target.value})} onBlur={() => patch({description:project.description})} className="mt-2 w-full rounded-xl border p-3" placeholder="What is this project about?" /><h2 className="mt-5 text-lg font-semibold">Objective</h2><textarea rows={4} value={project.objective || ''} onChange={(e) => setProject({...project, objective:e.target.value})} onBlur={() => patch({objective:project.objective})} className="mt-2 w-full rounded-xl border p-3" /></div><div><h2 className="text-lg font-semibold">Timeline</h2><input value={project.timeline || ''} onChange={(e) => setProject({...project,timeline:e.target.value})} onBlur={() => patch({timeline:project.timeline})} className="mt-2 w-full rounded-xl border p-3" placeholder="Q3 2026 – Q1 2027" /><h2 className="mt-5 text-lg font-semibold">Alfred's overview</h2><p className="mt-2 whitespace-pre-line text-slate-700">{project.ai_overview || 'Upload a project document and Alfred will build an evidence-based overview.'}</p><h2 className="mt-6 text-lg font-semibold">Files</h2>{uploadError && <p className="mt-2 rounded-lg bg-red-50 p-3 text-sm text-red-700">{uploadError}</p>}<div className="mt-2 space-y-2">{project.documents?.map((doc) => <div key={doc.id} className="rounded-lg bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><a className="min-w-0 truncate text-blue-700" href={`${apiUrl}/api/projects/${project.id}/documents/${doc.id}?user_number=${encodeURIComponent(userNumber)}`}>{doc.filename}</a><span className={`shrink-0 rounded-full px-2 py-1 text-xs font-semibold ${doc.processing_status === 'ready' ? 'bg-green-100 text-green-800' : doc.processing_status === 'failed' ? 'bg-red-100 text-red-800' : 'bg-blue-100 text-blue-800'}`}>{doc.processing_status === 'ready' ? 'Context added' : doc.processing_status === 'failed' ? 'Needs attention' : doc.processing_status === 'analyzing' ? 'Alfred is analyzing' : 'Reading document'}</span></div>{doc.processing_error && <div className="mt-2 text-sm text-red-700"><p>{doc.processing_error}</p><button onClick={() => retryDocument(doc.id)} className="mt-1 font-semibold underline">Retry analysis</button></div>}</div>)}{!project.documents?.length && <p className="text-slate-500">No project files yet.</p>}</div></div></div>}
    {tab === 'Workplan' && <ListEditor title="Workstreams and activities" values={project.workplan} onChange={(workplan) => {setProject({...project,workplan}); patch({workplan});}} placeholder="One workstream or activity per line" />}
    {tab === 'Scope & Deliverables' && <div className="grid gap-6 lg:grid-cols-3"><ListEditor title="In Scope" values={project.in_scope} onChange={(in_scope) => {setProject({...project,in_scope}); patch({in_scope});}} /><ListEditor title="Out of Scope" values={project.out_of_scope} onChange={(out_of_scope) => {setProject({...project,out_of_scope}); patch({out_of_scope});}} /><ListEditor title="Deliverables" values={project.deliverables} onChange={(deliverables) => {setProject({...project,deliverables}); patch({deliverables});}} /></div>}
    {tab === 'Team & Stakeholders' && <div className="grid gap-6 lg:grid-cols-2"><ListEditor title="Core Team" values={project.core_team} onChange={(core_team) => {setProject({...project,core_team}); patch({core_team});}} /><ListEditor title="Client Stakeholders" values={project.client_stakeholders} onChange={(client_stakeholders) => {setProject({...project,client_stakeholders}); patch({client_stakeholders});}} /></div>}
    {tab === 'Meetings' && <div><div className="flex justify-between"><div><h2 className="text-lg font-semibold">Project meetings</h2><p className="mt-1 text-sm text-slate-500">These are the existing Meeting Notes records linked to this project.</p></div><button onClick={() => setMeetingModal(true)} className="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Record Meeting</button></div><div className="mt-5 divide-y">{project.meetings?.map((item) => <button key={item.id} onClick={() => loadMeeting(item.id)} className="grid w-full gap-2 py-4 text-left hover:bg-slate-50 md:grid-cols-[150px_1.2fr_1fr_2fr]"><span className="text-sm text-slate-500">{item.started_at ? new Date(item.started_at).toLocaleDateString() : 'No date'}</span><span className="font-semibold">{item.title}</span><span className="text-sm text-slate-600">{item.participants?.join(', ') || '—'}</span><span className="text-sm text-slate-600">{item.one_line_summary || 'Processing…'}</span></button>)}{!project.meetings?.length && <p className="py-8 text-center text-slate-500">No meetings linked yet.</p>}</div></div>}
    {tab === 'Risks' && <ListEditor title="Project risks" values={project.risks} onChange={(risks) => {setProject({...project,risks}); patch({risks});}} placeholder="One risk per line" />}
  </div>{modal && <ProjectForm project={project} onSave={save} onCancel={() => setModal(false)} />}{meetingModal && <AddMeetingModal apiUrl={apiUrl} userNumber={userNumber} projectId={project.id} onClose={() => setMeetingModal(false)} onCreated={({id}) => {setMeetingModal(false); loadProject(project.id); loadMeeting(id);}} />}</div>;
}
